CREATE TABLE IF NOT EXISTS NUE_INDEX_USER
(
	ID			VARCHAR(255) CHARACTER SET ascii	NOT NULL	COMMENT 'ID',
	ENTITY_ID	CHAR(36) CHARACTER SET ascii		NOT NULL	COMMENT '実体ID',
	PRIMARY KEY (ID, ENTITY_ID),
	FOREIGN KEY (ENTITY_ID) REFERENCES NUE_ENTITIES(ID) ON UPDATE CASCADE ON DELETE CASCADE
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ユーザ アカウント索引';
