CREATE TABLE IF NOT EXISTS NUE_ACCESS
(
	ID			INTEGER	UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'アクセスID',
	USER_ID		CHAR(36)												COMMENT 'ユーザ アカウントID',
	DAILY_ID	CHAR(40)			NOT NULL							COMMENT 'デイリー ユニークID',
	MODULE		VARCHAR(255)		NOT NULL							COMMENT '使用したプラグイン',
	TAG			VARCHAR(255)											COMMENT '表示したタグ',
	TOPIC		VARCHAR(255)											COMMENT '表示したトピック',
	REMOTE_HOST	VARCHAR(255)		NOT NULL DEFAULT 'localhost'		COMMENT 'リモートホスト',
	REMOTE_ADDR	VARCHAR(16)			NOT NULL DEFAULT '127.0.0.1'		COMMENT 'IPアドレス',
	USER_AGENT	VARCHAR(255)		NOT NULL DEFAULT ''					COMMENT 'ユーザ エージェント',
	REFERER		VARCHAR(255)											COMMENT 'リファラ',
	ACCESSED	TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP	COMMENT 'アクセス日時'
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='アクセス ログ';
