CREATE TABLE IF NOT EXISTS NUE_INDEX_TAG
(
	NAME		VARCHAR(255)					NOT NULL	COMMENT 'タグ名',
	ENTITY_ID	CHAR(36) CHARACTER SET ascii	NOT NULL	COMMENT '実体ID',
	PRIMARY KEY (NAME, ENTITY_ID),
	FOREIGN KEY (ENTITY_ID) REFERENCES NUE_ENTITIES(ID) ON UPDATE CASCADE ON DELETE CASCADE
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='タグ索引';
